"""Canonical database of known group Cayley tables.

SINGLE SOURCE OF TRUTH for all group-theory data in MathWeaver.
Both ``handler.py`` and ``nl_translator.py`` import from here.

Design rationale (post-mortem):
    Previously, ``handler._TEST_GROUPS`` and ``nl_translator._KNOWN_GROUPS``
    each maintained a separate copy of the same data.  When one copy was
    updated (e.g. the Q8 Cayley table fix), the other could silently diverge.
    Consolidating into one module eliminates that class of bug entirely.

Every table here is verified by ``tests/test_golden_reference_math.py``
against all four group axioms (closure, identity, inverses, associativity)
plus the abelian / cyclic classification.  If you add a new group, the
golden tests will automatically validate it.
"""

from __future__ import annotations

from typing import TypedDict


class GroupMeta(TypedDict):
    """Metadata describing a known group.

    Attributes:
        name: Human-readable name (e.g. "Z₃", "S₃", "Q₈").
        order: The order of the group (number of elements).
        abelian: Whether the group is commutative.
        cyclic: Whether the group is cyclic (generated by a single element).
        description: Brief mathematical description.
    """

    name: str
    order: int
    abelian: bool
    cyclic: bool
    description: str


# ---------------------------------------------------------------------------
# Cayley tables
# ---------------------------------------------------------------------------
# Index convention: the row index is the left operand, the column index is
# the right operand.  Entry table[i][j] = (i * j) using 0-based indexing
# where 0 is always the identity element.
# ---------------------------------------------------------------------------

KNOWN_GROUPS: dict[str, list[list[int]]] = {
    # Z₂ — cyclic group of order 2 (addition mod 2), abelian
    "z2": [
        [0, 1],
        [1, 0],
    ],
    # Z₃ — cyclic group of order 3 (addition mod 3), abelian
    "z3": [
        [0, 1, 2],
        [1, 2, 0],
        [2, 0, 1],
    ],
    # Z₄ — cyclic group of order 4 (addition mod 4), abelian
    "z4": [
        [0, 1, 2, 3],
        [1, 2, 3, 0],
        [2, 3, 0, 1],
        [3, 0, 1, 2],
    ],
    # Klein four-group V₄ ≅ Z₂ × Z₂ (order 4, abelian, non-cyclic)
    "klein": [
        [0, 1, 2, 3],
        [1, 0, 3, 2],
        [2, 3, 0, 1],
        [3, 2, 1, 0],
    ],
    # Z₅ — cyclic group of order 5 (addition mod 5), abelian, prime order
    "z5": [
        [0, 1, 2, 3, 4],
        [1, 2, 3, 4, 0],
        [2, 3, 4, 0, 1],
        [3, 4, 0, 1, 2],
        [4, 0, 1, 2, 3],
    ],
    # S₃ — symmetric group on 3 letters (order 6, non-abelian, non-cyclic)
    "s3": [
        [0, 1, 2, 3, 4, 5],
        [1, 0, 3, 2, 5, 4],
        [2, 4, 0, 5, 1, 3],
        [3, 5, 1, 4, 0, 2],
        [4, 2, 5, 0, 3, 1],
        [5, 3, 4, 1, 2, 0],
    ],
    # Z₆ — cyclic group of order 6 (addition mod 6), abelian
    "z6": [
        [0, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 0],
        [2, 3, 4, 5, 0, 1],
        [3, 4, 5, 0, 1, 2],
        [4, 5, 0, 1, 2, 3],
        [5, 0, 1, 2, 3, 4],
    ],
    # Z₇ — cyclic group of order 7 (addition mod 7), abelian, prime order
    "z7": [
        [0, 1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6, 0],
        [2, 3, 4, 5, 6, 0, 1],
        [3, 4, 5, 6, 0, 1, 2],
        [4, 5, 6, 0, 1, 2, 3],
        [5, 6, 0, 1, 2, 3, 4],
        [6, 0, 1, 2, 3, 4, 5],
    ],
    # Q₈ — quaternion group (order 8, non-abelian, non-cyclic)
    # Index mapping: 0=1, 1=-1, 2=i, 3=-i, 4=j, 5=-j, 6=k, 7=-k
    # Key relations: i²=j²=k²=-1, ij=k, jk=i, ki=j (and anti-commute)
    "q8": [
        [0, 1, 2, 3, 4, 5, 6, 7],  # 1 * row
        [1, 0, 3, 2, 5, 4, 7, 6],  # -1 * row
        [2, 3, 1, 0, 6, 7, 5, 4],  # i * row
        [3, 2, 0, 1, 7, 6, 4, 5],  # -i * row
        [4, 5, 7, 6, 1, 0, 2, 3],  # j * row
        [5, 4, 6, 7, 0, 1, 3, 2],  # -j * row
        [6, 7, 4, 5, 3, 2, 1, 0],  # k * row
        [7, 6, 5, 4, 2, 3, 0, 1],  # -k * row
    ],
}


# ---------------------------------------------------------------------------
# Ground-truth metadata
# ---------------------------------------------------------------------------
# This is the authoritative classification.  The golden tests verify that
# each Cayley table matches its declared properties.
# ---------------------------------------------------------------------------

GROUP_META: dict[str, GroupMeta] = {
    "z2": {
        "name": "Z₂",
        "order": 2,
        "abelian": True,
        "cyclic": True,
        "description": "二阶循环群，同构于 {0,1} 配合模 2 加法",
    },
    "z3": {
        "name": "Z₃",
        "order": 3,
        "abelian": True,
        "cyclic": True,
        "description": "三阶循环群（素数阶），同构于模 3 加法",
    },
    "z4": {
        "name": "Z₄",
        "order": 4,
        "abelian": True,
        "cyclic": True,
        "description": "四阶循环群，同构于模 4 加法",
    },
    "klein": {
        "name": "V₄",
        "order": 4,
        "abelian": True,
        "cyclic": False,
        "description": "Klein 四元群，同构于 Z₂ × Z₂",
    },
    "z5": {
        "name": "Z₅",
        "order": 5,
        "abelian": True,
        "cyclic": True,
        "description": "五阶循环群（素数阶），同构于模 5 加法",
    },
    "s3": {
        "name": "S₃",
        "order": 6,
        "abelian": False,
        "cyclic": False,
        "description": "三次对称群，最小的非交换群",
    },
    "z6": {
        "name": "Z₆",
        "order": 6,
        "abelian": True,
        "cyclic": True,
        "description": "六阶循环群，同构于 Z₂ × Z₃",
    },
    "z7": {
        "name": "Z₇",
        "order": 7,
        "abelian": True,
        "cyclic": True,
        "description": "七阶循环群（素数阶），同构于模 7 加法",
    },
    "q8": {
        "name": "Q₈",
        "order": 8,
        "abelian": False,
        "cyclic": False,
        "description": "四元数群 {±1, ±i, ±j, ±k}，非交换",
    },
}


# ---------------------------------------------------------------------------
# Convenience: orders for which at least one known group exists
# ---------------------------------------------------------------------------

def known_orders() -> set[int]:
    """Return the set of orders for which at least one known group exists."""
    return {len(table) for table in KNOWN_GROUPS.values()}


def groups_of_order(order: int) -> list[tuple[str, list[list[int]]]]:
    """Return all known groups of the given order.

    Returns an empty list if no known group has that order — callers
    should treat this as "undecidable" rather than "confirmed".
    """
    return [
        (name, table)
        for name, table in KNOWN_GROUPS.items()
        if len(table) == order
    ]
