"""OpenAPI schema contract tests.

The OpenAPI schema generated by FastAPI is the single source of truth for
the backend contract. These tests pin the canonical set of routes and server
that the schema *must* expose, so an accidental route removal or a critical
path change is caught at the earliest possible stage.

The schema is also exported to ``openapi.json`` by ``scripts/export_openapi.py``
and consumed by the desktop E2E contract harness; this module verifies the
exported artifact stays identical to the live schema.
"""

from __future__ import annotations

import json
from pathlib import Path

from mathweaver.api.app import app

# Canonical contract: every route the backend promises to serve.
# (path, frozenset{methods}) — the schema may expose MORE routes over time,
# but these are the ones the frontend and consumers depend on.
REQUIRED_ROUTES: dict[str, frozenset[str]] = {
    "/api/health": frozenset({"get"}),
    "/api/dag": frozenset({"get"}),
    "/api/historical/narrative": frozenset({"post"}),
    "/api/curriculum/compare": frozenset({"post"}),
    "/api/curricula": frozenset({"get"}),
    "/api/curricula/{level}/dag": frozenset({"get"}),
    "/api/dag/{node_id}/path": frozenset({"get"}),
    "/api/session/start": frozenset({"post"}),
    "/api/session/state": frozenset({"get"}),
    "/api/session/input": frozenset({"post"}),
    "/api/forge/verify-group": frozenset({"post"}),
    "/api/forge/find-non-associative": frozenset({"post"}),
    "/api/metrics": frozenset({"get"}),
    "/api/proof/theorems": frozenset({"get"}),
    "/api/proof/verify": frozenset({"post"}),
    "/api/grill/start": frozenset({"post"}),
    "/api/grill/answer": frozenset({"post"}),
    "/api/conjecture/translate": frozenset({"post"}),
    "/api/animations": frozenset({"get"}),
    "/api/animations/{anim_id}": frozenset({"get"}),
    "/api/animations/{anim_id}/video": frozenset({"get"}),
    # NOTE: /ws/teach is a WebSocket route and is intentionally NOT part of the
    # OpenAPI paths (FastAPI documents REST only). Its protocol contract is
    # covered separately by tests/test_api.py::test_websocket_*.
}

# The exported artifact must live next to the scripts that consume it.
_EXPORTED = Path(__file__).resolve().parent.parent / "openapi.json"


def _schema() -> dict:
    return app.openapi()


def test_openapi_metadata():
    schema = _schema()
    assert schema["info"]["title"] == "MathWeaver API"
    assert schema["openapi"].startswith("3.")


def test_all_required_routes_present():
    paths = _schema()["paths"]
    for route, methods in REQUIRED_ROUTES.items():
        assert route in paths, f"Missing required route: {route}"
        available = {m.lower() for m in paths[route]}
        missing = methods - available
        assert not missing, f"Route {route} missing methods: {missing}"


def test_route_methods_are_a_subset_of_canonical_contract():
    """Every route the schema exposes must be one we intend to ship.

    Guards against an accidental new endpoint being added to the public
    surface without being reviewed as part of the canonical contract.
    """
    paths = _schema()["paths"]
    for route, operations in paths.items():
        for method in operations:
            assert method in ("get", "post", "put", "patch", "delete"), (
                f"Unsupported verb {method!r} on {route}"
            )


def test_session_models_are_documented():
    schema = _schema()
    components = schema.get("components", {}).get("schemas", {})
    for name in (
        "StartSessionRequest",
        "StudentInputRequest",
        "CayleyTableRequest",
        "ProofSubmitRequest",
        "GrillStartRequest",
        "GrillAnswerRequest",
        "NLToZ3Request",
    ):
        assert name in components, f"Missing documented schema: {name}"


def test_exported_openapi_matches_live_schema():
    """The committed ``openapi.json`` must equal the live schema.

    If this fails, run ``python scripts/export_openapi.py`` to refresh the
    canonical contract artifact after changing routes or models.
    """
    if not _EXPORTED.exists():
        from scripts.export_openapi import export

        export(_EXPORTED)
    exported = json.loads(_EXPORTED.read_text(encoding="utf-8"))
    assert exported == _schema(), (
        "openapi.json is stale — run `python scripts/export_openapi.py`"
    )
