"""Dynamic question generator: LLM-powered question creation.

When the static question bank doesn't have a question for a concept,
this module generates one using the LLM, based on:
- Concept metadata (name, description, learning objectives, examples)
- Target difficulty level (from AdaptiveDifficulty engine)
- Curriculum level (elementary → group_theory)
- Student profile (mastery level, known weak areas)

Quality validation:
- Question must be non-empty and 10-500 characters
- Answer must be non-empty and 10-2000 characters
- Question should reference the concept or its domain
- Difficulty should be within ±0.2 of target

Generated questions are cached per concept for reuse.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Any

from ..models.state import ConceptNode
from ..llm.client import extract_content

logger = logging.getLogger(__name__)


@dataclass
class GeneratedQuestion:
    """A question generated by the LLM."""

    question: str
    recommended_answer: str
    difficulty: float
    question_type: str  # "concept", "application", "edge_case"
    concept_node_id: str
    concept_name: str
    generation_method: str = "llm"  # "llm" or "template_fallback"

    def to_dict(self) -> dict[str, Any]:
        return {
            "question": self.question,
            "answer": self.recommended_answer,
            "difficulty": self.difficulty,
            "type": self.question_type,
            "concept_node_id": self.concept_node_id,
            "concept_name": self.concept_name,
            "generation_method": self.generation_method,
        }

    def to_bank_format(self) -> dict[str, Any]:
        """Convert to the format used by the static question bank."""
        return {
            "question": self.question,
            "answer": self.recommended_answer,
            "difficulty": self.difficulty,
            "type": self.question_type,
        }


# Difficulty-to-difficulty-description mapping for prompt engineering
_DIFFICULTY_DESCRIPTIONS = {
    (0.0, 0.2): "非常简单，适合入门检查，只需回忆定义或基本事实",
    (0.2, 0.4): "简单，考察对概念的基本理解",
    (0.4, 0.6): "中等难度，需要运用概念解决简单问题",
    (0.6, 0.8): "较难，需要综合运用多个概念或进行推理",
    (0.8, 1.0): "挑战性，需要深入理解和创造性思维",
}


def _difficulty_to_description(difficulty: float) -> str:
    """Map numeric difficulty to a description for the LLM prompt."""
    for (low, high), desc in _DIFFICULTY_DESCRIPTIONS.items():
        if low <= difficulty <= high:
            return desc
    return "中等难度"


# Question type templates for prompt variety
_QUESTION_TYPES = {
    "concept": "概念理解题：考察学生对概念定义和本质的理解",
    "application": "应用题：考察学生运用概念解决实际问题的能力",
    "edge_case": "边界情况题：考察学生对特殊情况或反例的理解",
    "proof": "证明题：要求学生给出简短的论证或推导",
}


class QuestionGenerator:
    """Generates math questions dynamically using LLM.

    Usage:
        gen = QuestionGenerator(llm_client=client)
        q = await gen.generate(
            concept_node=node,
            target_difficulty=0.5,
            curriculum_level="group_theory",
            student_profile={"mastery": 0.3, "weak_areas": ["inverse_element"]},
        )
    """

    def __init__(self, llm_client: Any = None) -> None:
        self.llm_client = llm_client
        # Cache: concept_node_id → list of generated questions
        self._cache: dict[str, list[GeneratedQuestion]] = {}
        self._generation_count = 0

    @property
    def cache_size(self) -> int:
        return sum(len(qs) for qs in self._cache.values())

    @property
    def generation_count(self) -> int:
        return self._generation_count

    async def generate(
        self,
        concept_node: ConceptNode,
        target_difficulty: float,
        curriculum_level: str = "group_theory",
        student_profile: dict[str, Any] | None = None,
        question_type: str = "concept",
    ) -> GeneratedQuestion:
        """Generate a question for a concept at the target difficulty.

        Falls back to template-based generation if LLM is unavailable.
        """
        student_profile = student_profile or {}

        # Try LLM generation first
        if self.llm_client is not None:
            try:
                q = await self._generate_with_llm(
                    concept_node,
                    target_difficulty,
                    curriculum_level,
                    student_profile,
                    question_type,
                )
                if q is not None:
                    self._cache.setdefault(concept_node.id, []).append(q)
                    self._generation_count += 1
                    logger.info(
                        "Generated question for %s (difficulty=%.2f, method=llm)",
                        concept_node.id,
                        target_difficulty,
                    )
                    return q
            except Exception as e:
                logger.warning("LLM question generation failed: %s, using template", e)

        # Fallback: template-based generation
        q = self._generate_template(concept_node, target_difficulty, question_type)
        self._cache.setdefault(concept_node.id, []).append(q)
        self._generation_count += 1
        return q

    async def _generate_with_llm(
        self,
        node: ConceptNode,
        difficulty: float,
        level: str,
        profile: dict[str, Any],
        q_type: str,
    ) -> GeneratedQuestion | None:
        """Use LLM to generate a question."""
        diff_desc = _difficulty_to_description(difficulty)
        type_desc = _QUESTION_TYPES.get(q_type, _QUESTION_TYPES["concept"])

        # Build context from concept metadata
        context_parts = [f"概念名称: {node.name}", f"概念描述: {node.description}"]
        if node.learning_objectives:
            context_parts.append(f"学习目标: {', '.join(node.learning_objectives[:3])}")
        if node.examples:
            context_parts.append(f"示例: {', '.join(node.examples[:2])}")
        if node.common_misconceptions:
            context_parts.append(f"常见误区: {', '.join(node.common_misconceptions[:2])}")
        if node.prerequisites:
            context_parts.append(f"先修概念: {', '.join(node.prerequisites[:3])}")

        # Add student profile context
        mastery = profile.get("mastery", 0.5)
        weak_areas = profile.get("weak_areas", [])
        profile_str = f"学生掌握度: {mastery:.0%}"
        if weak_areas:
            profile_str += f"，薄弱环节: {', '.join(weak_areas[:3])}"

        system_prompt = (
            "你是一位经验丰富的数学教师，擅长根据学生的水平生成恰当的问题。"
            "你需要生成一个数学问题和参考答案，以 JSON 格式回复。\n"
            "回复格式: {\"question\": \"问题文本\", \"answer\": \"参考答案\", \"difficulty\": 难度值}\n"
            "难度值是 0.0 到 1.0 之间的浮点数。\n"
            "问题应该简洁明了，参考答案应该准确且具有教学价值。"
        )

        user_message = (
            f"课程级别: {level}\n"
            f"难度要求: {diff_desc} (目标难度值: {difficulty:.2f})\n"
            f"题型: {type_desc}\n"
            f"学生信息: {profile_str}\n\n"
            f"概念信息:\n{chr(10).join(context_parts)}\n\n"
            f"请生成一道关于「{node.name}」的{q_type}题，难度约{difficulty:.2f}。"
            f"只回复 JSON，不要添加其他内容。"
        )

        resp = await self.llm_client.chat(
            system_prompt=system_prompt,
            user_message=user_message,
            temperature=0.8,
        )
        llm_text = extract_content(resp)

        return self._parse_llm_response(llm_text, node, difficulty, q_type)

    def _parse_llm_response(
        self,
        text: str,
        node: ConceptNode,
        target_difficulty: float,
        q_type: str,
    ) -> GeneratedQuestion | None:
        """Parse LLM response into a GeneratedQuestion, with validation."""
        # Extract JSON from response
        json_str = self._extract_json(text)
        if not json_str:
            logger.debug("No JSON found in LLM response (using template fallback)")
            return None

        try:
            data = json.loads(json_str)
        except json.JSONDecodeError:
            logger.warning("Invalid JSON in LLM response")
            return None

        question = data.get("question", "").strip()
        answer = data.get("answer", "").strip()
        difficulty = data.get("difficulty", target_difficulty)

        # Validate
        if not self._validate_question(question, answer, node):
            return None

        # Clamp difficulty
        try:
            difficulty = float(difficulty)
            difficulty = max(0.0, min(1.0, difficulty))
        except (TypeError, ValueError):
            difficulty = target_difficulty

        return GeneratedQuestion(
            question=question,
            recommended_answer=answer,
            difficulty=difficulty,
            question_type=q_type,
            concept_node_id=node.id,
            concept_name=node.name,
            generation_method="llm",
        )

    def _extract_json(self, text: str) -> str | None:
        """Extract the first JSON object from text."""
        # Try to find JSON between braces
        start = text.find("{")
        if start == -1:
            return None
        # Find matching closing brace
        depth = 0
        for i in range(start, len(text)):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    return text[start : i + 1]
        return None

    def _validate_question(
        self,
        question: str,
        answer: str,
        node: ConceptNode,
    ) -> bool:
        """Validate generated question quality."""
        if len(question) < 10 or len(question) > 500:
            logger.warning("Question length invalid: %d", len(question))
            return False
        if len(answer) < 10 or len(answer) > 2000:
            logger.warning("Answer length invalid: %d", len(answer))
            return False
        # Check that the question is not just echoing the concept name
        if question.strip() == node.name:
            return False
        return True

    def _generate_template(
        self,
        node: ConceptNode,
        difficulty: float,
        q_type: str,
    ) -> GeneratedQuestion:
        """Generate a question using templates when LLM is unavailable."""
        templates = {
            "concept": (
                f"请解释「{node.name}」的含义，并给出一个具体例子。",
                f"{node.description}。"
                + (f" 示例: {node.examples[0]}。" if node.examples else "")
                + (f" 学习目标: {node.learning_objectives[0]}。" if node.learning_objectives else ""),
            ),
            "application": (
                f"如何在实际问题中应用「{node.name}」？请说明步骤。",
                f"应用{node.name}的关键在于理解其前提条件和适用范围。"
                f" {node.description}",
            ),
            "edge_case": (
                f"关于「{node.name}」，有哪些容易混淆的特殊情况或边界条件？",
                f"常见误区包括: {', '.join(node.common_misconceptions[:2]) if node.common_misconceptions else '需要注意概念的前提条件和限制'}。"
                f" {node.description}",
            ),
            "proof": (
                f"请证明或验证关于「{node.name}」的一个基本性质。",
                f"证明思路: {node.description}"
                + (f" 相关定理: {', '.join(node.related_theorems[:2])}。" if node.related_theorems else ""),
            ),
        }

        q_text, a_text = templates.get(q_type, templates["concept"])
        return GeneratedQuestion(
            question=q_text,
            recommended_answer=a_text,
            difficulty=difficulty,
            question_type=q_type,
            concept_node_id=node.id,
            concept_name=node.name,
            generation_method="template_fallback",
        )

    def get_cached_questions(self, concept_node_id: str) -> list[GeneratedQuestion]:
        """Get previously generated questions for a concept."""
        return self._cache.get(concept_node_id, [])

    def get_all_generated(self) -> dict[str, list[dict[str, Any]]]:
        """Export all generated questions for persistence/inspection."""
        return {
            cid: [q.to_dict() for q in qs]
            for cid, qs in self._cache.items()
        }

    def to_dict(self) -> dict[str, Any]:
        """Serialize generator state for metrics."""
        return {
            "generation_count": self._generation_count,
            "cache_size": self.cache_size,
            "cached_concepts": list(self._cache.keys()),
        }
